name: Build, Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd src
          npm ci
          npm run-script deploy

      # - name: Unit Tests
      #   run: |
      #     cd src
      #     npm run-script test
  deploy:
    name: Deploy
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: src/dist/open-delivery-menu-web




